name: Close Issue if Creator Didn't Star Repo

on:
  issues:
    types: [opened, reopened]

jobs:
  check-star:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user has starred the repo
        id: check_star
        uses: octokit/request-action@v2
        with:
          route: GET /repos/{owner}/{repo}/stargazers
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          per_page: 100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find if user has starred the repo
        id: user_has_starred
        run: |
          user="${{ github.event.issue.user.login }}"
          stargazers=$(echo "${{ steps.check_star.outputs.data }}" | jq -r '.[].login')
          if echo "$stargazers" | grep -q "$user"; then
            echo "User $user has starred the repo."
            echo "has_star=true" >> $GITHUB_ENV
          else
            echo "User $user has NOT starred the repo."
            echo "has_star=false" >> $GITHUB_ENV
          fi

      - name: Add comment if user has not starred the repo
        if: env.has_star == 'false'
        run: |
          COMMENT="Hello @${{ github.event.issue.user.login }}, in order to create issues in this repository, you need to star it first. Please star the repo and reopen the issue."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"body": "'"$COMMENT"'"}' \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/issues/${{ github.event.issue.number }}/comments"

      - name: Close issue if user has not starred the repo
        if: env.has_star == 'false'
        uses: octokit/request-action@v2
        with:
          route: PATCH /repos/{owner}/{repo}/issues/{issue_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.issue.number }}
          state: closed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
